service: afsdigitaltools-endpoint

frameworkVersion: ">=1.2.0 <2.0.0"

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

plugins:
  - serverless-google-cloudfunctions

provider:
  name: google
  runtime: python37
  project: afsdigitaltools
  credentials: ~/.gcloud/credentials.json # path must be absolute

functions:
  survey_endpoint:
    handler: survey_endpoint
    events:
      - http: path